### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by goxr3plus** [theshteves/commit-bot#3]
What i need is to just add a space character at the end of readme file of a repo i have , so i have at least 1 contribution per day.

Is that possible with this ? Do  i need to have the computer opened or it can execute somehow i can put in cloud and proxy it ?

**Comment by theshteves** [comment]
@goxr3plus thanks for asking!

Right now, it does just that except by adding the current date & time on a new line.

**I'll add a "Getting Started" guide to the README :+1:**

This is designed to be run locally from your own computer & only while it is open. While I could make a lot of other more robust methods, there's something uniquely organic & believable about the randomness of days where you are & aren't on your computer at a specific time that better represent a realistic amount of GitHub activity.

Let me know if you have any other fun ideas!

**Comment by theshteves** [comment]
Added "Getting Started" guide to README: https://github.com/theshteves/commit-bot/commit/78946ef5551b392fa26a7e7d532845734658a0f2
